# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Npm@1
      inputs:
        command: 'custom'
        customCommand: 'install @projecthoneycomb/focus-tools -g'
    - script: mkdir tracks
      displayName: 'Make tracks folder'
    - script: manifest-to-files --i="./manifest.json" --o="./tracks"
      displayName: 'Resolve manifest'
    - task: Docker@2
      inputs:
        containerRegistry: 'Focus Mode Registry'
        repository: 'stream-lofi'
        command: 'buildAndPush'
        Dockerfile: '**/lofi/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest