# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build_lofi
    displayName: Build Lofi
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Npm@1
      inputs:
        command: 'custom'
        customCommand: 'install @projecthoneycomb/focus-tools --save-dev'
    - script: curl https://focustrackcache.blob.core.windows.net/cache/lofi/tracks.zip --output $(Agent.TempDirectory)/tracks.zip
      displayName: Download cache
    - script: mkdir tracks
      displayName: Make ./tracks
    - task: ExtractFiles@1
      inputs:
        archiveFilePatterns: '$(Agent.TempDirectory)/tracks.zip'
        destinationFolder: './lofi/tracks'
        cleanDestinationFolder: false

    - script: npx manifest-to-files --i="./lofi/manifest.json" --o="./lofi/tracks"
      displayName: 'Resolve manifest'
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: './lofi/tracks'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Agent.TempDirectory)/cache/tracks.zip'
        replaceExistingArchive: true
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Honeycomb Main (ef492f20-94bd-47a4-83d2-01e200c463a6)'
        scriptType: bash
        scriptLocation: 'inlineScript'
        inlineScript: 'az storage blob upload-batch -s $(Agent.TempDirectory)/cache/ --account-name focustrackcache -d cache --destination-path lofi'
    - task: Docker@2
      inputs:
        containerRegistry: 'Focus Mode Registry'
        repository: 'stream-lofi'
        command: 'buildAndPush'
        Dockerfile: '**/lofi/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest
  - job: Build_electronic
    displayName: Build Electronic
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Npm@1
      inputs:
        command: 'custom'
        customCommand: 'install @projecthoneycomb/focus-tools --save-dev'
    - script: curl https://focustrackcache.blob.core.windows.net/cache/electronic/tracks.zip --output $(Agent.TempDirectory)/tracks.zip
      displayName: Download cache
    - script: mkdir tracks
      displayName: Make ./tracks
    - task: ExtractFiles@1
      inputs:
        archiveFilePatterns: '$(Agent.TempDirectory)/tracks.zip'
        destinationFolder: './electronic/tracks'
        cleanDestinationFolder: false
    - script: npx manifest-to-files --i="./electronic/manifest.json" --o="./electronic/tracks"
      displayName: 'Resolve manifest'
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: './electronic/tracks'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Agent.TempDirectory)/cache/tracks.zip'
        replaceExistingArchive: true
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Honeycomb Main (ef492f20-94bd-47a4-83d2-01e200c463a6)'
        scriptType: bash
        scriptLocation: 'inlineScript'
        inlineScript: 'az storage blob upload-batch -s $(Agent.TempDirectory)/cache/ --account-name focustrackcache -d cache --destination-path electronic'
    - task: Docker@2
      inputs:
        containerRegistry: 'Focus Mode Registry'
        repository: 'stream-electronic'
        command: 'buildAndPush'
        Dockerfile: '**/electronic/Dockerfile'
        tags: |
          latest